"""Read-only local Evo observatory data.

The endpoint reads a deliberately small, sanitized snapshot generated by the
benchmark harness. It never executes Evo commands and never mutates an
experiment, which keeps the commissioning API separated from the optimizer.
"""

import json
import os
from pathlib import Path
from typing import Any

from fastapi import APIRouter, Depends
from smart_commissioning_core.rbac import Role

from app.core.auth import require_role

router = APIRouter()

_PROTECTED_RELEASE = "v0.1.40"
_PROTECTED_COMMIT = "b3b2f764b78449dae2f5232cd7aab1f2d47c30eb"


def _snapshot_path() -> Path:
    configured = os.environ.get("EVO_OBSERVATORY_PATH", "").strip()
    if configured:
        return Path(configured).expanduser().resolve()
    return (Path.cwd() / ".evo" / "observatory.json").resolve()


def _pending_snapshot() -> dict[str, Any]:
    return {
        "workspace_status": "not_initialized",
        "protected_release": _PROTECTED_RELEASE,
        "protected_commit": _PROTECTED_COMMIT,
        "target": "core/smart_commissioning_core/udmi_validation.py",
        "metric": "Correct findings first; runtime and memory second",
        "baseline": None,
        "experiments": [],
        "selected_experiment_id": None,
        "updated_at": None,
    }


@router.get("/overview", dependencies=[Depends(require_role(Role.VIEWER))])
def get_evo_overview() -> dict[str, Any]:
    """Return the latest sanitized Evo snapshot or an honest pending state."""

    path = _snapshot_path()
    if not path.is_file():
        return _pending_snapshot()
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError):
        pending = _pending_snapshot()
        pending["workspace_status"] = "snapshot_unavailable"
        return pending
    if not isinstance(payload, dict):
        pending = _pending_snapshot()
        pending["workspace_status"] = "snapshot_unavailable"
        return pending
    return {**_pending_snapshot(), **payload}
