"""engine framework discovery tables and cancel flag

Revision ID: c4a7ced176a9
Revises: c9663f90f68a
Create Date: 2026-06-12 15:21:04.458047

Adds the cooperative-cancellation flag (runs.cancel_requested) and the three
generic discovery result tables (discovered_devices, discovered_points,
discovered_topics) used by the shared engine framework
(smart_commissioning_core.engines). Autogenerated against SQLite from
smart_commissioning_core.db.models, then hand-adjusted:

  * UTCDateTime columns are emitted as plain DateTime(timezone=True) at the DDL
    level (matching the initial migration; the application type decorator only
    matters in Python).
  * runs.cancel_requested gets server_default='0' so the NOT NULL add succeeds
    on a table that already has rows (existing runs default to not-cancelled).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c4a7ced176a9"
down_revision: str | None = "c9663f90f68a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "discovered_devices",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.String(length=255), nullable=True),
        sa.Column("site_id", sa.String(length=255), nullable=True),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("device_type", sa.String(length=128), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("vendor", sa.String(length=255), nullable=True),
        sa.Column("model", sa.String(length=255), nullable=True),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_discovered_devices_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discovered_devices")),
    )
    with op.batch_alter_table("discovered_devices", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_discovered_devices_run_id"), ["run_id"], unique=False)
        batch_op.create_index(
            "ix_discovered_devices_run_position", ["run_id", "position"], unique=False
        )

    op.create_table(
        "discovered_points",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("device_ref", sa.String(length=255), nullable=True),
        sa.Column("point_id", sa.String(length=255), nullable=True),
        sa.Column("point_name", sa.String(length=255), nullable=True),
        sa.Column("observed_value", sa.JSON(), nullable=False),
        sa.Column("units", sa.String(length=64), nullable=True),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_discovered_points_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discovered_points")),
    )
    with op.batch_alter_table("discovered_points", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_discovered_points_run_id"), ["run_id"], unique=False)
        batch_op.create_index(
            "ix_discovered_points_run_position", ["run_id", "position"], unique=False
        )

    op.create_table(
        "discovered_topics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("topic", sa.String(length=512), nullable=False),
        sa.Column("last_payload", sa.JSON(), nullable=False),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_discovered_topics_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discovered_topics")),
    )
    with op.batch_alter_table("discovered_topics", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_discovered_topics_run_id"), ["run_id"], unique=False)
        batch_op.create_index(
            "ix_discovered_topics_run_position", ["run_id", "position"], unique=False
        )

    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "cancel_requested",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )


def downgrade() -> None:
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_column("cancel_requested")

    with op.batch_alter_table("discovered_topics", schema=None) as batch_op:
        batch_op.drop_index("ix_discovered_topics_run_position")
        batch_op.drop_index(batch_op.f("ix_discovered_topics_run_id"))
    op.drop_table("discovered_topics")

    with op.batch_alter_table("discovered_points", schema=None) as batch_op:
        batch_op.drop_index("ix_discovered_points_run_position")
        batch_op.drop_index(batch_op.f("ix_discovered_points_run_id"))
    op.drop_table("discovered_points")

    with op.batch_alter_table("discovered_devices", schema=None) as batch_op:
        batch_op.drop_index("ix_discovered_devices_run_position")
        batch_op.drop_index(batch_op.f("ix_discovered_devices_run_id"))
    op.drop_table("discovered_devices")
