"""initial schema

Revision ID: c9663f90f68a
Revises:
Create Date: 2026-06-11 21:21:43.660551

Creates projects, sites, runs, run_issues, configuration_snapshots, and
import_records. Autogenerated against SQLite from
smart_commissioning_core.db.models, then verified by hand. The application's
UTCDateTime columns are plain DateTime(timezone=True) at the DDL level.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c9663f90f68a"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "configuration_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.String(length=255), nullable=False),
        sa.Column("site_id", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_configuration_snapshots")),
        sa.UniqueConstraint(
            "project_id", "site_id", "version", name=op.f("uq_configuration_snapshots_project_id")
        ),
    )
    with op.batch_alter_table("configuration_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            "ix_configuration_snapshots_project_site", ["project_id", "site_id"], unique=False
        )

    op.create_table(
        "import_records",
        sa.Column("import_id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=255), nullable=True),
        sa.Column("site_id", sa.String(length=255), nullable=True),
        sa.Column("import_type", sa.String(length=64), nullable=False),
        sa.Column("original_filename", sa.String(length=512), nullable=False),
        sa.Column("stored_file_path", sa.String(length=1024), nullable=False),
        sa.Column("summary", sa.JSON(), nullable=False),
        sa.Column("accepted_rows", sa.JSON(), nullable=False),
        sa.Column("errors", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("import_id", name=op.f("pk_import_records")),
    )
    with op.batch_alter_table("import_records", schema=None) as batch_op:
        batch_op.create_index("ix_import_records_project_site", ["project_id", "site_id"], unique=False)

    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )

    op.create_table(
        "sites",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("project_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], name=op.f("fk_sites_project_id_projects")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sites")),
    )
    with op.batch_alter_table("sites", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sites_project_id"), ["project_id"], unique=False)

    op.create_table(
        "runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=255), nullable=False),
        sa.Column("site_id", sa.String(length=255), nullable=False),
        sa.Column("job_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("stage", sa.String(length=128), nullable=False),
        sa.Column("progress_percent", sa.Integer(), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("result_summary", sa.JSON(), nullable=False),
        sa.Column("execution_mode", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], name=op.f("fk_runs_project_id_projects")),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], name=op.f("fk_runs_site_id_sites")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
    )
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_runs_project_site_created", ["project_id", "site_id", "created_at"], unique=False
        )
        batch_op.create_index("ix_runs_status", ["status"], unique=False)

    op.create_table(
        "run_issues",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("issue_id", sa.String(length=128), nullable=False),
        sa.Column("asset_id", sa.String(length=255), nullable=True),
        sa.Column("issue_type", sa.String(length=128), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=True),
        sa.Column("point_name", sa.String(length=255), nullable=True),
        sa.Column("topic", sa.String(length=512), nullable=True),
        sa.Column("expected_value", sa.Text(), nullable=True),
        sa.Column("observed_value", sa.Text(), nullable=True),
        sa.Column("match_basis", sa.String(length=64), nullable=True),
        sa.Column("suggested_action", sa.Text(), nullable=True),
        sa.Column("raw_evidence_uri", sa.String(length=1024), nullable=True),
        sa.Column("status_detail", sa.String(length=255), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_run_issues_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_issues")),
    )
    with op.batch_alter_table("run_issues", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_run_issues_run_id"), ["run_id"], unique=False)


def downgrade() -> None:
    with op.batch_alter_table("run_issues", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_run_issues_run_id"))
    op.drop_table("run_issues")

    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_index("ix_runs_status")
        batch_op.drop_index("ix_runs_project_site_created")
    op.drop_table("runs")

    with op.batch_alter_table("sites", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sites_project_id"))
    op.drop_table("sites")

    op.drop_table("projects")

    with op.batch_alter_table("import_records", schema=None) as batch_op:
        batch_op.drop_index("ix_import_records_project_site")
    op.drop_table("import_records")

    with op.batch_alter_table("configuration_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_configuration_snapshots_project_site")
    op.drop_table("configuration_snapshots")
