#Requires -Version 7.0
# Generate infra/.env from infra/.env.example, filling every CHANGE_ME slot
# with a fresh cryptographically random 32-byte hex secret. Refuses to
# overwrite an existing infra/.env. POSIX twin: scripts/bootstrap-env.sh.
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$Infra   = Join-Path (Split-Path -Parent $PSScriptRoot) 'infra'
$EnvFile = Join-Path $Infra '.env'

if (Test-Path $EnvFile) {
    Write-Host "REFUSED: $EnvFile already exists; not overwriting a deployed config."
    Write-Host 'Move it away first if you really want fresh secrets (this rotates ALL of them).'
    exit 1
}

function New-HexSecret {
    $bytes = [byte[]]::new(32)
    [System.Security.Cryptography.RandomNumberGenerator]::Fill($bytes)
    [System.BitConverter]::ToString($bytes).Replace('-', '').ToLowerInvariant()
}

$apiKey = ''
$lines = foreach ($line in Get-Content (Join-Path $Infra '.env.example')) {
    if ($line -match '^(\w+)=.*CHANGE_ME') {
        $secret = New-HexSecret
        if ($Matches[1] -eq 'API_KEY') { $apiKey = $secret }
        "$($Matches[1])=$secret"
    } else { $line }
}
Set-Content -Path $EnvFile -Value (@('# Generated by scripts/bootstrap-env.ps1 -- do not commit.') + $lines)

Write-Host "Wrote $EnvFile with fresh random secrets."
Write-Host "API_KEY (paste into the app's 'Set API key' dialog): $apiKey"
Write-Host 'Next: docker compose -f infra/docker-compose.yml --env-file infra/.env up -d --build'
