#!/bin/sh
# Generate infra/.env from infra/.env.example, filling every CHANGE_ME slot
# with a fresh cryptographically random 32-byte hex secret. Refuses to
# overwrite an existing infra/.env. Windows twin: scripts/bootstrap-env.ps1.
set -eu

root=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
envfile="$root/infra/.env"

if [ -e "$envfile" ]; then
  echo "REFUSED: $envfile already exists; not overwriting a deployed config." >&2
  echo "Move it away first if you really want fresh secrets (this rotates ALL of them)." >&2
  exit 1
fi

# ponytail: od over /dev/urandom instead of openssl -- POSIX tools only, zero extra deps.
hex_secret() { od -An -N32 -tx1 /dev/urandom | tr -d ' \n'; }

api_key=''
{
  echo '# Generated by scripts/bootstrap-env.sh -- do not commit.'
  while IFS= read -r line; do
    case $line in
      [A-Za-z_]*=*CHANGE_ME*)
        name=${line%%=*}; secret=$(hex_secret)
        if [ "$name" = API_KEY ]; then api_key=$secret; fi
        line="$name=$secret" ;;
    esac
    printf '%s\n' "$line"
  done < "$root/infra/.env.example"
} > "$envfile.tmp" && mv "$envfile.tmp" "$envfile"

echo "Wrote $envfile with fresh random secrets."
echo "API_KEY (paste into the app's 'Set API key' dialog): $api_key"
echo "Next: docker compose -f infra/docker-compose.yml --env-file infra/.env up -d --build"
